# Generated by Django 2.2.17 on 2021-06-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('memtest', models.CharField(max_length=32)),
                ('homo_linpack', models.CharField(max_length=32)),
                ('heter_linpack', models.CharField(max_length=32)),
                ('heter_dgemm', models.CharField(max_length=32)),
                ('heter_stream', models.CharField(max_length=32)),
            ],
        ),
    ]
