# Generated by Django 2.2.17 on 2021-06-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0002_auto_20210610_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='cab',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
