# Generated by Django 2.2.17 on 2021-06-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0003_node_cab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='heter_dgemm',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='node',
            name='heter_linpack',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='node',
            name='heter_stream',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='node',
            name='homo_linpack',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='node',
            name='memtest',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
